[package]
name = "schemask_derive"
version = "0.1.4"
edition = "2024"
license = "ISC"
repository = "https://github.com/andrewbaxter/schemask"
readme = "../../readme.md"
description = "Simple but powerful data schemas (derive macro crate)"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-crate = "3"
quote = "1"
syn = { version = "2", features = ["full"] }

[lints.clippy]
all = "allow"
