[package]
name = "test_gen_rust"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
schemask = { version = "0.1.1", path = ".." }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
schemask = { version = "0.1.1", path = ".." }

[lints.clippy]
all = "allow"
