[package]
name = "schemask_core"
version = "0.1.4"
edition = "2024"
license = "ISC"
repository = "https://github.com/andrewbaxter/schemask"
readme = "../../readme.md"
description = "Simple but powerful data schemas (core model and generators)"

[dependencies]
schemask_derive = { version = "0.1.4", path = "../schemask_derive" }
genemichaels-lib = "0.8"
heck = "0.5"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = { version = "2", features = ["full"] }

[lints.clippy]
all = "allow"
