[workspace]
members = ["schemask_derive", "test_gen_rust", "test_gen_typescript"]

[package]
name = "schemask"
version = "0.1.0"
edition = "2024"

[dependencies]
schemask_derive = { path = "schemask_derive" }
aargvark = { version = "0.9", features = ["serde_json"] }
flowcontrol = "0.2"
genemichaels-lib = "0.8"
loga = "0.5"
proc-macro2 = "1"
quote = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints.clippy]
all = "allow"
